apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: app
  labels:
    name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-db
  template:
    metadata:
      labels:
        name: mysql-db
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user-password
        envFrom:
          - configMapRef:
              name: mysql-config
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
