apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deploy
  labels:
    app: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resultserver-deploy
  template:
    metadata:
      labels:
        name: resultserver-deploy
    spec:
      containers:
        - name: resultserver
          image: devopsfatih/resultserver
          ports:
          - containerPort: 80
          env:
            - name: MYSQL_DATABASE_HOST
              value: mysql-service
            - name: MYSQL_DATABASE
              value: "phonebook"
            - name: MYSQL_USER
              value: "fatih"
            - name: MYSQL_PASSWORD
              value: "sifre123"
